shared:
    image: node:18
jobs:
    SIMPLE:
        steps:
            - echo: echo test
        requires: [~pr, ~commit]
    PARALLEL1:
        steps:
            - echo: echo test
        requires: [~SIMPLE]
    PARALLEL2:
        steps:
            - echo: echo test
        requires: [~SIMPLE]
    JOIN:
        steps:
            - echo: echo test
        requires: [~PARALLEL1, ~PARALLEL2]
    FAIL:
        steps:
            - echo: exit 1;
        requires: [~commit]
    AFTER-FAIL:
        steps:
            - echo: echo test
        requires: [~FAIL]
